In [1]:
3-2

[1] 1

# m simple math in R

In [2]:
# simple math in R

sin(4)

In [3]:
sin(4)

[1] -0.7568025

In [4]:
4 == 3

[1] FALSE

!(4 == 4)

In [5]:
!(4 == 4)

[1] FALSE

In [6]:
(4 == 4) && (3 >2)

[1] TRUE

# variable assignment


In [7]:
a <- 3 + 3

In [8]:
print (a)

[1] 6


In [9]:
greetings <- "hey,buddy!"

In [10]:
print (greetings)

[1] "hey,buddy!"


In [11]:
some_logic <- TRUE 

# The Vector

In [12]:
dat <- c(4,5,6,23,2)

In [13]:
print(dat)

[1]  4  5  6 23  2


In [14]:
v1 <- c(1,2,3)
v2 <- c(5,4,3)
v <- c(v1,v2)

In [15]:
print (v)

[1] 1 2 3 5 4 3


In [16]:
my_vec <- rep(0,10)

In [17]:
print (my_vet)

ERROR: Error in print(my_vet): object 'my_vet' not found


In [18]:
print (my_vec)

 [1] 0 0 0 0 0 0 0 0 0 0


In [19]:
m <- 1:20

In [20]:
m

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [21]:
v3 <- seq(-10:-5)

In [22]:
v3

[1] 1 2 3 4 5 6

In [23]:
v3<- (-10,10,2)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:10: unexpected ','
1: v3<- (-10,
             ^


In [24]:
v3 <- seq(-10,10,2)

In [25]:
print (v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [26]:
v3

[1] -10  -8  -6  -4  -2   0   2   4   6   8  10

In [27]:
v3 <- seq(-10,10,2), v3

ERROR: Error in parse(text = x, srcfile = src): <text>:1:20: unexpected ','
1: v3 <- seq(-10,10,2),
                       ^


In [28]:
v3 <- seq(-10,10,2)
print(v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [29]:
print(seq(-10,10,2))

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [30]:
(call it u) <- (02,2)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:7: unexpected symbol
1: (call it
          ^


In [31]:
u <- (-2,2)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:9: unexpected ','
1: u <- (-2,
            ^


In [32]:
u<-(-2,2,1)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:7: unexpected ','
1: u<-(-2,
          ^


In [33]:
u <- seq(-2,2,1)

In [34]:
print (u)

[1] -2 -1  0  1  2


# indexing and slicing

In [35]:
v <- rnorm(5)

In [36]:
v

[1] -0.8074274  0.5697962  0.3528247  1.2988158 -2.0255016

In [37]:
v[2]

[1] 0.5697962

In [38]:
v[1:3]

[1] -0.8074274  0.5697962  0.3528247

In [39]:
v [4]

[1] 1.298816

In [40]:
v[2:5]

[1]  0.5697962  0.3528247  1.2988158 -2.0255016

In [47]:
indces <- c(1,3)
v [c(1,3)]

[1] -0.8074274  0.3528247

In [42]:
print (v)

[1] -0.8074274  0.5697962  0.3528247  1.2988158 -2.0255016


In [43]:
v[-3]

[1] -0.8074274  0.5697962  1.2988158 -2.0255016

In [44]:
print [v(-3)]

ERROR: Error in v(-3): could not find function "v"


In [45]:
print (v[3])

[1] 0.3528247


In [46]:
print (v[-3])

[1] -0.8074274  0.5697962  1.2988158 -2.0255016


# assignment with indexing

In [48]:
u<- c(5,6,8,22)

In [49]:
u [1] <- 0

In [50]:
print (u)

[1]  0  6  8 22


In [53]:
u3 <- u[1:3]

In [54]:
print (u3)

[1] 0 6 8


In [55]:
v <- (10,20,30)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:9: unexpected ','
1: v <- (10,
            ^


In [56]:
v <-[10,20,30]

ERROR: Error in parse(text = x, srcfile = src): <text>:1:5: unexpected '['
1: v <-[
        ^


In [59]:
v <- seq(10,20,30)

In [60]:
print (v)

[1] 10


In [61]:
v <- seq(10,30,10)

In [62]:
print (v)

[1] 10 20 30


In [63]:
v [1:2]<- 0


In [64]:
print (v)

[1]  0  0 30


In [65]:
v1 <- seq(10,50,10)

In [66]:
print (v1)

[1] 10 20 30 40 50


In [80]:
idx <- c(1,3,5)
v2 <- v1[c(1,3,5)]


In [82]:
v2 <- v1[c(-2,-4)]

In [83]:
print(v2)

[1] 10 30 50


In [84]:
v1 <- seq(10,50,10)
idx <- c(TRUE,FALSE,TRUE,FALSE,TRUE)
V2 <- v1[idx]
print (v2)

[1] 10 30 50


# vectorization of operations

In [85]:
v <- c(44,55,66)

In [86]:
v - 20

[1] 24 35 46

In [87]:
print (v-20)

[1] 24 35 46


In [88]:
v >50

[1] FALSE  TRUE  TRUE

# useful operations on vectors

In [89]:
v <- rnorm(10)

In [90]:
print (v)

 [1]  0.40770825 -2.29533158 -0.16555340 -0.45968046  0.68634648 -0.20944021
 [7] -0.08534528 -0.94587430 -1.58304220  1.91966229


In [91]:
length(v)

[1] 10

In [93]:
n <- length(v)

In [94]:
sum(v)

[1] -2.73055

In [95]:
max(v)

[1] 1.919662

In [96]:
min(v)

[1] -2.295332

In [97]:
sd(v)

[1] 1.180203

In [98]:
s <- sd(v)

In [99]:
print(s)

[1] 1.180203


In [100]:
xbar <- mean(v)

In [101]:
print (xbar)

[1] -0.273055


# the matrix

In [102]:
x1 <- c(4,5,6)
x2 <- c(55,55,77)

In [103]:
m <- cbind(x1,x2)

In [104]:
print (m) # m is a 3*2 matrix

     x1 x2
[1,]  4 55
[2,]  5 55
[3,]  6 77


In [105]:
m2 <- rbind(x1,x2)

In [106]:
print (m2)

   [,1] [,2] [,3]
x1    4    5    6
x2   55   55   77


In [110]:
a <- matrix (0,nrow=5,ncol=3)

In [111]:
print(a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0


In [112]:
dat <- rnorm(15)

In [113]:
b<- matrix(dat, ncol = 3)

In [114]:
print (b)

           [,1]        [,2]       [,3]
[1,]  0.6415286  0.63419383  1.2950940
[2,]  0.2855308  0.05803343 -0.4308151
[3,]  1.0343545  0.92113408  0.5822438
[4,]  0.4885654 -2.10229631 -0.8381675
[5,] -0.3106783 -0.10196179  1.2443926


# indexing in matrices

In [115]:
dat <- sample(12)

In [116]:
dat

[1]  1  9  2  4  6  8  7 10  3  5 12 11

In [117]:
m <- matrix (dat, ncol = 3)

In [118]:
print(m)

     [,1] [,2] [,3]
[1,]    1    6    3
[2,]    9    8    5
[3,]    2    7   12
[4,]    4   10   11


In [119]:
m[1,2] #row在前面column在后面

[1] 6

In [120]:
m[2,3]

[1] 5

In [121]:
m[1:2,3]

[1] 3 5

In [122]:
m[1, ]

[1] 1 6 3

In [123]:
m[, 3]<-0

In [124]:
print (m)

     [,1] [,2] [,3]
[1,]    1    6    0
[2,]    9    8    0
[3,]    2    7    0
[4,]    4   10    0


In [125]:
m[1:2,2] <- 99

In [126]:
print (m)

     [,1] [,2] [,3]
[1,]    1   99    0
[2,]    9   99    0
[3,]    2    7    0
[4,]    4   10    0


In [127]:
print (m)

     [,1] [,2] [,3]
[1,]    1   99    0
[2,]    9   99    0
[3,]    2    7    0
[4,]    4   10    0


In [128]:
nrow(m)

[1] 4

In [129]:
num_rows <- nrow(m)

In [130]:
ncol(m)

[1] 3

In [131]:
num_col <- ncol(m)

In [132]:
colMeans(m)

[1]  4.00 53.75  0.00

In [133]:
colSums(m)

[1]  16 215   0

# the dataframe 

In [134]:
id <- seq(4)

In [135]:
score <- rnorm(4)

In [136]:
names <- c("john","paul","george","ringo")

In [137]:
vocals <-c(TRUE,TRUE,FALSE,FALSE)

In [143]:
dset <-data.frame(id,names,score,vocals, stringsAsFactors = FALSE)

In [139]:
print(dset)

  id  names       score vocals
1  1   john -0.52891442   TRUE
2  2   paul  0.00620376   TRUE
3  3 george  0.23743034  FALSE
4  4  ringo  1.04026680  FALSE


In [144]:
dset [1,2]

[1] "john"

In [145]:
dset$names

[1] "john"   "paul"   "george" "ringo"

In [142]:
dset$vocals

[1]  TRUE  TRUE FALSE FALSE